import { randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Mppx, tempo } from "mppx/server";
import {
  ALL_NETWORKS,
  DEFAULT_FACILITATOR_URL,
  DEFAULT_TESTNET_FACILITATOR_URL,
  TEMPO_NETWORKS,
  X402_SUPPORTED_NETWORKS,
} from "./assets.js";
import { ConfigError } from "./errors.js";
import type {
  AgentPaymentsConfig,
  CustomAssetDef,
  Protocol,
  ResolvedConfig,
  ResolvedMppConfig,
  ResolvedX402Config,
} from "./types.js";
import { buildAssetRegistry, getAssetNetworkInfo, inferNetworks } from "./utils.js";

const PAYAI_DIR = ".payai";
const MPP_SECRET_FILE = "mpp-secret";
const GITIGNORE_FILE = ".gitignore";
/**
 * Written into .payai/.gitignore so the MPP secret key (and anything else we
 * persist) cannot be committed by accident — protects users who haven't
 * added `.payai/` to their repo-level .gitignore.
 */
const GITIGNORE_CONTENT =
  "# Auto-generated by @payai/agentic-payments.\n" +
  "# Contains the MPP HMAC secret; never commit.\n" +
  "*\n";

/**
 * Resolve user config into a fully normalized ResolvedConfig.
 * Handles mode detection (managed/manual), address expansion, and MPP secret auto-generation.
 */
export async function resolveConfig(config: AgentPaymentsConfig): Promise<ResolvedConfig> {
  // `live: true` → mainnet; anything else (including undefined) → testnet.
  // Defaulting to testnet keeps local dev safe — no real payments without opt-in.
  const testnet = !(config.live ?? false);

  // --- Mode detection ---
  if (config.apiKey) {
    // Managed mode — fetch config from PayAI API
    // TODO: Implement when PayAI API is available
    throw new ConfigError(
      "Managed mode (apiKey) is not yet implemented. Use manual mode with payTo instead.",
    );
  }

  // Manual mode — infer from payTo
  if (!config.payTo) {
    throw new ConfigError("Either apiKey (managed mode) or payTo (manual mode) is required.");
  }

  // Resolve static payTo for config purposes (functions are resolved per-request)
  const staticPayTo = typeof config.payTo === "function" ? undefined : config.payTo;

  // --- Network inference ---
  // Global `networks` = the pool of chains payTo is expanded across, plus what
  // adapters see in ctx.networks. Each protocol adapter intersects this with
  // its own supported set (x402 does so via ResolvedX402Config.supportedNetworks).
  let networks: string[];
  if (config.networks) {
    networks = config.networks;
  } else if (staticPayTo) {
    networks = inferNetworks(staticPayTo, testnet);
  } else {
    // Dynamic payTo — use all networks for the environment
    networks = [...ALL_NETWORKS[testnet ? "testnet" : "mainnet"]];
  }

  // --- Protocol inference ---
  // MPP currently only has a Tempo implementation, so enabling it requires a Tempo network.
  const tempoNetwork =
    networks.find((n) => n === TEMPO_NETWORKS.mainnet) ??
    networks.find((n) => n === TEMPO_NETWORKS.testnet);
  const protocols: Protocol[] = config.protocols ?? (tempoNetwork ? ["x402", "mpp"] : ["x402"]);

  // --- Asset registry + default accepted assets ---
  const assetRegistry = buildAssetRegistry(config.assets);
  const defaultAssets = config.assets
    ? config.assets.map((a) => (typeof a === "string" ? a : a.name))
    : ["USDC"];

  // --- x402 config ---
  let x402: ResolvedX402Config | null = null;
  if (protocols.includes("x402")) {
    x402 = {
      facilitatorUrl:
        config.x402?.facilitatorUrl ??
        (testnet ? DEFAULT_TESTNET_FACILITATOR_URL : DEFAULT_FACILITATOR_URL),
      scheme: config.x402?.scheme ?? "exact",
      // Default: every network PayAI's x402 facilitator supports for the env.
      // Override via `x402.networks` when running against a different facilitator.
      supportedNetworks: config.x402?.networks ?? [
        ...X402_SUPPORTED_NETWORKS[testnet ? "testnet" : "mainnet"],
      ],
    };
  }

  // --- MPP config ---
  let mpp: ResolvedMppConfig | null = null;
  if (protocols.includes("mpp") && tempoNetwork) {
    validateMppDescriptions(config.endpoints);
    const secretKey = await resolveMppSecretKey(config.mpp?.secretKey);
    const realm = config.mpp?.realm ?? inferRealm();

    // Pre-configure one tempo.charge method per registered asset on Tempo.
    // Recipient + amount + description are supplied per-request by the adapter
    // (supports dynamic payTo and per-asset pricing).
    const methods = config.mpp?.methods ?? buildTempoMethods(assetRegistry, tempoNetwork);

    const mppxInstance = Mppx.create({
      methods: methods as Parameters<typeof Mppx.create>[0]["methods"],
      secretKey,
      realm,
    });

    mpp = { secretKey, realm, mppx: mppxInstance };
  }

  return {
    endpoints: config.endpoints,
    payTo: config.payTo,
    networks,
    protocols,
    assetRegistry,
    defaultAssets,
    x402,
    mpp,
  };
}

/**
 * Resolve MPP secret key from config, env, file, or auto-generate.
 */
async function resolveMppSecretKey(configKey?: string): Promise<string> {
  // 1. Explicit config
  if (configKey) return configKey;

  // 2. Environment variable
  const envKey = process.env.MPP_SECRET_KEY;
  if (envKey) return envKey;

  // 3. Persisted file
  const secretPath = join(process.cwd(), PAYAI_DIR, MPP_SECRET_FILE);
  try {
    const saved = await readFile(secretPath, "utf-8");
    const trimmed = saved.trim();
    if (trimmed) return trimmed;
  } catch {
    // File doesn't exist — generate
  }

  // 4. Auto-generate and persist
  const generated = randomBytes(32).toString("hex");
  try {
    const dir = join(process.cwd(), PAYAI_DIR);
    await mkdir(dir, { recursive: true });
    // Drop a .gitignore inside .payai/ first so the secret file cannot be
    // accidentally committed, even if the user's repo-level .gitignore
    // doesn't list .payai/. Writing the gitignore before the secret means
    // the secret file is covered the moment it exists on disk.
    await ensurePayaiGitignore(dir);
    await writeFile(secretPath, `${generated}\n`, { mode: 0o600 });
    console.log(
      `[@payai/agentic-payments] Generated MPP secret key → .payai/mpp-secret\n` +
        `  A .gitignore was written inside .payai/ so this key won't be committed.\n` +
        `  To use across instances, set MPP_SECRET_KEY env var or mpp.secretKey in config.`,
    );
  } catch {
    // Can't persist — use ephemeral key, warn louder
    console.warn(
      `[@payai/agentic-payments] Could not persist MPP secret key to .payai/mpp-secret.\n` +
        `  Key is ephemeral — challenges won't survive restarts.\n` +
        `  Set MPP_SECRET_KEY env var or mpp.secretKey in config for persistence.`,
    );
  }

  return generated;
}

/**
 * Write .payai/.gitignore (contents: `*`) if it's missing. Idempotent — we
 * never clobber a user's existing file. This is the last line of defense
 * against committing the MPP HMAC secret.
 */
async function ensurePayaiGitignore(dir: string): Promise<void> {
  const gitignorePath = join(dir, GITIGNORE_FILE);
  try {
    await readFile(gitignorePath, "utf-8");
    // Already exists — don't overwrite.
    return;
  } catch {
    await writeFile(gitignorePath, GITIGNORE_CONTENT);
  }
}

/**
 * Build one pre-configured Tempo charge method per asset that has a Tempo address.
 * Recipient is NOT baked in — the adapter supplies it per-request so dynamic
 * payTo functions work the same as static addresses.
 */
function buildTempoMethods(
  registry: Record<string, CustomAssetDef>,
  tempoNetwork: string,
): unknown[] {
  const methods: unknown[] = [];
  for (const asset of Object.values(registry)) {
    const info = getAssetNetworkInfo(asset, tempoNetwork);
    if (!info) continue;
    methods.push(tempo.charge({ currency: info.address }));
  }
  return methods;
}

/**
 * Enforce ASCII-only endpoint descriptions when MPP is enabled.
 *
 * The MPP draft (paymentauth.org, draft-httpauth-payment-00) states descriptions
 * "may contain localized text" (UTF-8), but does not specify how non-ASCII is
 * transmitted in the WWW-Authenticate header. The inherited RFC 9110 auth-param
 * grammar permits only token / quoted-string, and Node's fetch implementation
 * (undici) enforces ByteString on header values — rejecting anything outside
 * 0x00-0x7F. Until the spec pins this down (RFC 8187 extension vs. strict ASCII)
 * we fail loud at config load time rather than silently dropping the MPP
 * challenge at request time.
 */
function validateMppDescriptions(endpoints: Record<string, { description?: string }>): void {
  const NON_ASCII = /[^\x20-\x7E]/;
  for (const [route, ep] of Object.entries(endpoints)) {
    if (!ep.description) continue;
    const match = ep.description.match(NON_ASCII);
    if (!match) continue;
    throw new ConfigError(
      `Endpoint "${route}" description contains a non-ASCII character (${JSON.stringify(match[0])} at index ${match.index}).\n` +
        `  MPP (paymentauth.org draft-httpauth-payment-00) allows UTF-8 descriptions but does not\n` +
        `  specify header-value encoding, and Node's fetch rejects non-ASCII header values.\n` +
        `  Fix: restrict the description to ASCII, or disable MPP for this endpoint via\n` +
        `  \`protocols: ["x402"]\` (x402 base64-encodes its challenge and handles UTF-8 fine).`,
    );
  }
}

/**
 * Infer the server realm from environment or default.
 */
function inferRealm(): string {
  return process.env.MPP_REALM ?? process.env.FLY_APP_NAME ?? process.env.VERCEL_URL ?? "localhost";
}
